PRODUCT_PACKAGES += \
    runlmbench \
    lmbench_lib \
    mhz \
    bw_file_rd \
    bw_mem \
    bw_mmap_rd \
    bw_pipe \
    bw_unix \
    lat_cmd \
    lat_ctx \
    lat_fcntl \
    lat_fs \
    lat_mem_rd \
    lat_mmap \
    lat_ops \
    lat_pipe \
    lat_pagefault \
    lat_proc \
    lat_rand \
    lat_sig \
    lat_syscall \
    lat_udp \
    lat_unix \
    lat_usleep \
    cache \
    line \
    lmdd \
    tlb \
    lmstream \
    memsize \
    lat_select \
    lat_unix_connect \
    lat_fifo \
    lat_http \
    par_mem \
    par_ops \
    enough \
